spring:
  profiles:
    active: ${profile.active}


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81